### PR TITLE
fix(deps): restrict curl-cffi version to <0.16.0

### LINKED ISSUE #963: [Bug]: cannot import name 'normalize_browser_type'
### Describe the bug

Fundus 0.5.7 fails during import when curl-cffi 0.16.0 is installed.

In version 0.16.0, normalize_browser_type was renamed to resolve_latest_browser_type (see https://github.com/lexiforest/curl_cffi/compare/v0.15.0...v0.16.0).

Works with curl-cffi<0.16.

### How to reproduce

```python
mkdir test_repo
cd test_repo

uv init --bare --python 3.13
uv add "fundus==0.5.7" "curl-cffi==0.16.0"
uv run python -c "import fundus"
```

### Expected behavior.

Import works.

### Logs and Stack traces

```stacktrace
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import fundus
  File "/home/USER/test_repo/.venv/lib/python3.13/site-packages/fundus/__init__.py", line 5, in <module>
    from fundus.publishers import PublisherCollection
  File "/home/USER/test_repo/.venv/lib/python3.13/site-packages/fundus/publishers/__init__.py", line 4, in <module>
    from fundus.publishers.at import AT
  File "/home/USER/test_repo/.venv/lib/python3.13/site-packages/fundus/publishers/at/__init__.py", line 3, in <module>
    from fundus.publishers.base_objects import Publisher, PublisherGroup
  File "/home/USER/test_repo/.venv/lib/python3.13/site-packages/fundus/publishers/base_objects.py", line 9, in <module>
    from curl_cffi.requests.impersonate import normalize_browser_type
ImportError: cannot import name 'normalize_browser_type' from 'curl_cffi.requests.impersonate' (/home/USER/test_repo/.venv/lib/python3.13/site-packages/curl_cffi/requests/impersonate.py)
```

### Screenshots

_No response_

### Additional Context

_No response_

### Environment

```markdown
- Fundus: 0.5.7
- curl-cffi: 0.16.0
- Python: 3.13.13
- uv: 0.11.9
- OS: Arch Linux x86_64
```

### PR DESCRIPTION
**Pull request by addie9800**
closes #963

### CODE REVIEW

**Review by MaxDall — APPROVED** [review]
@addie9800 Thanks for fixing this!
